"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

给新手的快速导读（你以后会经常改这些）：

- **DEBUG**：本地开发通常开；生产必须关（否则可能泄漏敏感信息）
- **ALLOWED_HOSTS**：允许哪些 Host 头/域名访问你的服务；生产必须配置
- **INSTALLED_APPS**：启用哪些“应用模块”（Django 自带/第三方/你自己的 app）
- **MIDDLEWARE**：请求/响应的中间处理链（安全、会话、CSRF、防点击劫持等）
- **DATABASES**：数据库连接配置（本地默认 sqlite；生产通常是 Postgres/MySQL）
- **TIME_ZONE / USE_TZ**：时区与时间存储策略
- **STATIC_URL**：静态资源路径（生产会配合 collectstatic/CDN）
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from .db import build_databases

# 项目根目录（`apps/server/`）。后面拼接路径建议都用它，避免硬编码相对路径。
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 `.env`（如果存在）。
#
# 说明：
# - 我们不会把真实的 `.env` 提交到仓库（避免泄漏密码）
# - 但本地开发时，你可以在 `apps/server/.env` 里写 Postgres 账号密码等配置
# - `override=False` 表示：如果你在系统环境变量里已经设置了同名变量，则以系统的为准
load_dotenv(dotenv_path=BASE_DIR / '.env', override=False)

def _require_bool_env(name: str) -> bool:
    """
    读取一个“必须显式配置”的布尔环境变量（fail-fast，不给默认值）。

    你提到“不希望 settings 里给默认值、以免掩盖错误”，所以这里采用强约束：
    - 变量不存在：直接抛错中断启动
    - 变量存在但值非法：直接抛错中断启动

    允许的值：
    - true:  1 / true / yes（大小写不敏感）
    - false: 0 / false / no
    """

    raw = os.getenv(name)
    if raw is None:
        raise RuntimeError(f"缺少必须的环境变量：{name}（请在 apps/server/.env 或系统环境变量中显式配置）")

    v = raw.strip().lower()
    if v in ("1", "true", "yes"):
        return True
    if v in ("0", "false", "no"):
        return False

    raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}。允许 1/0/true/false/yes/no")


# 全局“鉴权开关”（开发/初始化阶段专用）
# - OPEN_API_AUTH=1：放开所有 DRF API 的默认鉴权（相当于全局 AllowAny）
# - OPEN_API_AUTH=0：默认需要登录（更安全，生产推荐）
# 注意：这里不提供默认值，避免“没配却以为生效”。
OPEN_API_AUTH = _require_bool_env("OPEN_API_AUTH")

# Redis 用于 token 会话管理（refresh token 的服务端状态）
REDIS_URL = os.getenv("REDIS_URL")
if not REDIS_URL:
    raise RuntimeError(
        "缺少必须的环境变量：REDIS_URL（refresh token 会话依赖 Redis）。\n"
        "请在 apps/server/.env 或系统环境变量中配置，例如：REDIS_URL=redis://127.0.0.1:6379/0"
    )

# fail-fast：启动时就验证 Redis 可用（避免等到调用 login/refresh 才 500）
try:
    import redis  # type: ignore[import-not-found]

    _r = redis.Redis.from_url(REDIS_URL, decode_responses=True)
    _r.ping()
except Exception as e:
    raise RuntimeError(
        "Redis 连接失败，已拒绝启动（refresh token 会话依赖 Redis）。\n"
        f"当前 REDIS_URL={REDIS_URL!r}\n"
        "常见原因：\n"
        "- Redis 未启动 / 端口不通\n"
        "- Redis 开启了密码/ACL，但 REDIS_URL 未包含认证信息（例如 redis://:password@host:6379/0）\n"
        "- REDIS_URL 写错（host/port/db）\n"
        f"原始错误：{type(e).__name__}: {e}"
    ) from e


def _require_positive_int_env(name: str) -> int:
    raw = os.getenv(name)
    if raw is None:
        raise RuntimeError(f"缺少必须的环境变量：{name}（请在 apps/server/.env 或系统环境变量中显式配置）")
    try:
        v = int(raw.strip())
    except Exception as ex:
        raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}（必须是整数秒）") from ex
    if v <= 0:
        raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}（必须是正整数秒）")
    return v


# token 有效期（单位：秒）
ACCESS_TOKEN_EXPIRES_SECONDS = _require_positive_int_env("ACCESS_TOKEN_EXPIRES_SECONDS")
REFRESH_TOKEN_EXPIRES_SECONDS = _require_positive_int_env("REFRESH_TOKEN_EXPIRES_SECONDS")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 用于加密签名（比如 session/csrf token 等）。
# 生产环境务必放到环境变量/密钥管理系统里，不要写死在仓库。
SECRET_KEY = 'django-insecure-(s!m9#kf^0e9ywm1c&fy=3&9q4$q-$!uxom-63il@yg9$$57$^'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True 时：报错页面会展示更完整的调试信息（方便开发，但不适合线上）。
DEBUG = True

# 允许访问的域名（Host 头）。
#
# 背景（你刚遇到的报错）：
# - 你用 `runserver 0.0.0.0:PORT` 启动时，请求的 Host 头会是 `0.0.0.0:PORT`
# - Django 会做 Host 校验，如果不在 ALLOWED_HOSTS 中就会抛 `DisallowedHost`
#
# 企业项目建议：
# - 生产环境务必通过环境变量明确配置（避免 Host header 攻击）
# - 开发环境可以放行 localhost/127.0.0.1/0.0.0.0 方便联调
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    # 用逗号分隔：ALLOWED_HOSTS=example.com,api.example.com
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    # 默认开发白名单（不使用 '*'，避免养成坏习惯）
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

# Django 会根据 INSTALLED_APPS 注册模型、管理后台、模板、静态文件等能力。
# 后续你创建自己的 app（例如 `api`）也会加到这里。
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django REST Framework：让我们更容易写出规范的 JSON API（序列化、校验、权限等）
    'rest_framework',
    # OpenAPI/Swagger 文档（/api/schema/ + /api/docs/）
    'drf_spectacular',
    # 你自己的业务模块
    'customers',   # 客户用户模块（本次新增）
    'auth_api',    # 认证模块（login/token；暂时只做 login）
]

# 请求处理的“管道”。每个中间件都会按顺序处理 request / response。
# 例如 CSRF 校验、会话、认证、一些安全头等，都是在这里生效的。
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 全局路由入口模块（对应 `config/urls.py`）
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = build_databases(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 默认语言（影响 admin 后台、表单错误提示等）。
# 你如果希望中文界面，可以改成 'zh-hans'（或未来做多语言）。
LANGUAGE_CODE = 'zh-hans'

# 时区（建议按业务所在时区设置）。配合 USE_TZ=True，Django 内部会用 UTC 存储，
# 但展示时会按 TIME_ZONE 转换（我们在 utils.format_datetime 里也会做 localtime）。
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 是否启用时区支持。通常建议保持 True（数据库用 UTC 存，展示时按时区转换）。
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 日志（开发期先把错误打到控制台，便于你快速定位 500）
#
# 说明：
# - Django 本身在 DEBUG=True 时也会打印 traceback，但你现在有统一异常处理/统一返回格式，
#   我们希望无论如何都能在控制台看到异常栈。
# - 这里配置了一个名为 `vizon.api` 的 logger，专门给 API 异常使用。
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "loggers": {
        "vizon.api": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        }
    },
}


# Django REST Framework 的基础配置
#
# 这里先给一个“新手友好 + 足够可用”的默认值：
# - 认证：支持 Session（浏览器/后台）以及 Basic（调试方便；生产可以关掉）
# - 权限：默认需要登录；注册接口会在视图里单独放行
REST_FRAMEWORK = {
    # 统一 JSON 返回结构（对前端更友好；也避免每个接口都手动包装 Response）
    'DEFAULT_RENDERER_CLASSES': [
        'config.api.UnifiedJSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 客户 JWT（Authorization: Bearer <token>）
        'auth_api.authentication.CustomerJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 这里不靠“隐式默认”，而是由 OPEN_API_AUTH 显式决定
        'rest_framework.permissions.AllowAny' if OPEN_API_AUTH else 'rest_framework.permissions.IsAuthenticated',
    ],
    # OpenAPI schema 生成器（Swagger/Redoc 都依赖它）
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 统一异常输出（配合 Renderer 变成统一错误结构）
    'EXCEPTION_HANDLER': 'config.api.unified_exception_handler',
}

# drf-spectacular 的基础配置（先给最小可用集）
SPECTACULAR_SETTINGS = {
    "TITLE": "Vizon API",
    "DESCRIPTION": "Vizon 服务端接口文档",
    "VERSION": "0.0.1",
    # 文档里以相对路径展示；你如果后续上域名/网关，可再细化 SERVERS
    # Swagger UI 体验优化：页面刷新也保留 Authorization
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    # 声明 JWT Bearer 的安全方案，Swagger 才能显示 Authorize（填 token）
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    # 默认让接口带上 bearerAuth（具体接口也可在视图上覆盖）
    "SECURITY": [{"bearerAuth": []}],
}
