"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

给新手的快速导读（你以后会经常改这些）：

- **DEBUG**：本地开发通常开；生产必须关（否则可能泄漏敏感信息）
- **ALLOWED_HOSTS**：允许哪些 Host 头/域名访问你的服务；生产必须配置
- **INSTALLED_APPS**：启用哪些“应用模块”（Django 自带/第三方/你自己的 app）
- **MIDDLEWARE**：请求/响应的中间处理链（安全、会话、CSRF、防点击劫持等）
- **DATABASES**：数据库连接配置（本地默认 sqlite；生产通常是 Postgres/MySQL）
- **TIME_ZONE / USE_TZ**：时区与时间存储策略
- **STATIC_URL**：静态资源路径（生产会配合 collectstatic/CDN）
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from .db import build_databases

# 项目根目录（`apps/server/`）。后面拼接路径建议都用它，避免硬编码相对路径。
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 `.env`（如果存在）。
#
# 说明：
# - 我们不会把真实的 `.env` 提交到仓库（避免泄漏密码）
# - 但本地开发时，你可以在 `apps/server/.env` 里写 Postgres 账号密码等配置
# - `override=False` 表示：如果你在系统环境变量里已经设置了同名变量，则以系统的为准
load_dotenv(dotenv_path=BASE_DIR / ".env", override=False)


def _require_bool_env(name: str) -> bool:
    """
    读取一个“必须显式配置”的布尔环境变量（fail-fast，不给默认值）。

    你提到“不希望 settings 里给默认值、以免掩盖错误”，所以这里采用强约束：
    - 变量不存在：直接抛错中断启动
    - 变量存在但值非法：直接抛错中断启动

    允许的值：
    - true:  1 / true / yes（大小写不敏感）
    - false: 0 / false / no
    """

    raw = os.getenv(name)
    if raw is None:
        raise RuntimeError(
            f"缺少必须的环境变量：{name}（请在 apps/server/.env 或系统环境变量中显式配置）"
        )

    v = raw.strip().lower()
    if v in ("1", "true", "yes"):
        return True
    if v in ("0", "false", "no"):
        return False

    raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}。允许 1/0/true/false/yes/no")


# 客户 CRUD 灌数开关（开发/初始化阶段专用）
# - OPEN_API_AUTH=1：仅 /api/customers/ 免鉴权
# - OPEN_API_AUTH=0：客户接口也需 JWT（生产推荐）
# 资源 API（scenes/textures/models3d）始终在视图上强制鉴权，不受此开关影响。
OPEN_API_AUTH = _require_bool_env("OPEN_API_AUTH")

# Redis 用于 token 会话管理（refresh token 的服务端状态）
REDIS_URL = os.getenv("REDIS_URL")
if not REDIS_URL:
    raise RuntimeError(
        "缺少必须的环境变量：REDIS_URL（refresh token 会话依赖 Redis）。\n"
        "请在 apps/server/.env 或系统环境变量中配置，例如：REDIS_URL=redis://127.0.0.1:6379/0"
    )

# fail-fast：启动时就验证 Redis 可用（避免等到调用 login/refresh 才 500）
try:
    import redis  # type: ignore[import-not-found]

    _r = redis.Redis.from_url(REDIS_URL, decode_responses=True)
    _r.ping()
except Exception as e:
    raise RuntimeError(
        "Redis 连接失败，已拒绝启动（refresh token 会话依赖 Redis）。\n"
        f"当前 REDIS_URL={REDIS_URL!r}\n"
        "常见原因：\n"
        "- Redis 未启动 / 端口不通\n"
        "- Redis 开启了密码/ACL，但 REDIS_URL 未包含认证信息（例如 redis://:password@host:6379/0）\n"
        "- REDIS_URL 写错（host/port/db）\n"
        f"原始错误：{type(e).__name__}: {e}"
    ) from e


def _require_positive_int_env(name: str) -> int:
    raw = os.getenv(name)
    if raw is None:
        raise RuntimeError(
            f"缺少必须的环境变量：{name}（请在 apps/server/.env 或系统环境变量中显式配置）"
        )
    try:
        v = int(raw.strip())
    except Exception as ex:
        raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}（必须是整数秒）") from ex
    if v <= 0:
        raise RuntimeError(f"环境变量 {name} 值非法：{raw!r}（必须是正整数秒）")
    return v


# token 有效期（单位：秒）
ACCESS_TOKEN_EXPIRES_SECONDS = _require_positive_int_env("ACCESS_TOKEN_EXPIRES_SECONDS")
REFRESH_TOKEN_EXPIRES_SECONDS = _require_positive_int_env(
    "REFRESH_TOKEN_EXPIRES_SECONDS"
)

# 文件上传大小上限（字节），可被环境变量覆盖
FILE_UPLOAD_MAX_SIZE_TEXTURE = int(os.getenv("FILE_UPLOAD_MAX_SIZE_TEXTURE", 50 * 1024 * 1024))
FILE_UPLOAD_MAX_SIZE_MODEL = int(os.getenv("FILE_UPLOAD_MAX_SIZE_MODEL", 200 * 1024 * 1024))
FILE_UPLOAD_MAX_SIZE_SCENE = int(os.getenv("FILE_UPLOAD_MAX_SIZE_SCENE", 200 * 1024 * 1024))
FILE_UPLOAD_MAX_SIZE_THUMBNAIL = int(os.getenv("FILE_UPLOAD_MAX_SIZE_THUMBNAIL", 5 * 1024 * 1024))

# 列表 API 默认分页大小
API_PAGE_SIZE = int(os.getenv("API_PAGE_SIZE", "50"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _require_nonempty_env(name: str) -> str:
    """读取必须非空的环境变量（fail-fast）。"""
    raw = os.getenv(name)
    if raw is None or not str(raw).strip():
        raise RuntimeError(
            f"缺少必须的环境变量：{name}（请在 apps/server/.env 或系统环境变量中显式配置）"
        )
    return str(raw).strip()


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 用于加密签名（JWT / session / CSRF 等），禁止写死在仓库。
SECRET_KEY = _require_nonempty_env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True 时：报错页面会展示更完整的调试信息（方便开发，但不适合线上）。
DEBUG = _require_bool_env("DEBUG")

# 允许访问的域名（Host 头）。
#
# 背景（你刚遇到的报错）：
# - 你用 `runserver 0.0.0.0:PORT` 启动时，请求的 Host 头会是 `0.0.0.0:PORT`
# - Django 会做 Host 校验，如果不在 ALLOWED_HOSTS 中就会抛 `DisallowedHost`
#
# 企业项目建议：
# - 生产环境务必通过环境变量明确配置（避免 Host header 攻击）
# - 开发环境可以放行 localhost/127.0.0.1/0.0.0.0 方便联调
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    # 用逗号分隔：ALLOWED_HOSTS=example.com,api.example.com
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    # 默认开发白名单（不使用 '*'，避免养成坏习惯）
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

# Django 会根据 INSTALLED_APPS 注册模型、管理后台、模板、静态文件等能力。
# 后续你创建自己的 app（例如 `api`）也会加到这里。
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",
    # Django REST Framework：让我们更容易写出规范的 JSON API（序列化、校验、权限等）
    "rest_framework",
    # CORS 支持：允许前端开发服务器跨域访问 API 和媒体文件
    "corsheaders",
    # OpenAPI/Swagger 文档（/api/schema/ + /api/docs/）
    "drf_spectacular",
    # Django Channels：WebSocket 支持（压缩进度实时推送）
    # Celery 进度上报需要 django-celery-results 读取 AsyncResult
    # 这里使用 redis backend 即可，不需要额外 Django app
    # 你自己的业务模块
    "customers",  # 客户用户模块（本次新增）
    "auth_api",  # 认证模块（login/token；暂时只做 login）
    "scenes",  # 场景管理模块（保存/加载项目包）
    "textures",  # 贴图资源管理模块（上传/分类/预览）
    "models3d",  # 模型资源管理模块（上传/分类/列表）
]

# 媒体文件根目录（FileField/ImageField 上传存储位置）。
# 生产环境应配置为独立挂载点或对象存储；本地开发直接落在 apps/server/media/ 目录。
MEDIA_ROOT = BASE_DIR / "media"
# 媒体文件访问 URL 前缀；开发环境由 Django 直接伺服，生产环境交给 Nginx。
MEDIA_URL = "/media/"

# 请求处理的“管道”。每个中间件都会按顺序处理 request / response。
# 例如 CSRF 校验、会话、认证、一些安全头等，都是在这里生效的。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS 配置：允许前端开发服务器跨域访问 API 和媒体文件
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# 全局路由入口模块（对应 `config/urls.py`）
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Django Channels 通道层配置（Redis 后端，跨进程通信）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = build_databases(BASE_DIR)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 默认语言（影响 admin 后台、表单错误提示等）。
# 你如果希望中文界面，可以改成 'zh-hans'（或未来做多语言）。
LANGUAGE_CODE = "zh-hans"

# 时区（建议按业务所在时区设置）。配合 USE_TZ=True，Django 内部会用 UTC 存储，
# 但展示时会按 TIME_ZONE 转换（我们在 utils.format_datetime 里也会做 localtime）。
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

# 是否启用时区支持。通常建议保持 True（数据库用 UTC 存，展示时按时区转换）。
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 日志（开发期先把错误打到控制台，便于你快速定位 500）
#
# 说明：
# - Django 本身在 DEBUG=True 时也会打印 traceback，但你现在有统一异常处理/统一返回格式，
#   我们希望无论如何都能在控制台看到异常栈。
# - 这里配置了一个名为 `vizon.api` 的 logger，专门给 API 异常使用。
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "loggers": {
        "vizon.api": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Django REST Framework 的基础配置
#
# 这里先给一个“新手友好 + 足够可用”的默认值：
# - 认证：支持 Session（浏览器/后台）以及 Basic（调试方便；生产可以关掉）
# - 权限：默认需要登录；注册接口会在视图里单独放行
REST_FRAMEWORK = {
    # 统一 JSON 返回结构（对前端更友好；也避免每个接口都手动包装 Response）
    "DEFAULT_RENDERER_CLASSES": [
        "config.api.UnifiedJSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 客户 JWT（Authorization: Bearer <token>）
        "auth_api.authentication.CustomerJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "config.pagination.StandardResultsPagination",
    "PAGE_SIZE": API_PAGE_SIZE,
    # OpenAPI schema 生成器（Swagger/Redoc 都依赖它）
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 统一异常输出（配合 Renderer 变成统一错误结构）
    "EXCEPTION_HANDLER": "config.api.unified_exception_handler",
}

# drf-spectacular 的基础配置（先给最小可用集）
SPECTACULAR_SETTINGS = {
    "TITLE": "Vizon API",
    "DESCRIPTION": "Vizon 服务端接口文档",
    "VERSION": "0.0.1",
    # 文档里以相对路径展示；你如果后续上域名/网关，可再细化 SERVERS
    # Swagger UI 体验优化：页面刷新也保留 Authorization
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    # 声明 JWT Bearer 的安全方案，Swagger 才能显示 Authorize（填 token）
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    # 默认让接口带上 bearerAuth（具体接口也可在视图上覆盖）
    "SECURITY": [{"bearerAuth": []}],
}

# Celery 配置
# 去除 Redis URL 中的用户名，避免 ACL 受限用户无法使用 pub/sub
def _sanitize_redis_url(url: str) -> str:
    from urllib.parse import urlparse, urlunparse
    parsed = urlparse(url)
    if parsed.username:
        netloc = parsed.hostname or ""
        if parsed.port:
            netloc += f":{parsed.port}"
        if parsed.password:
            netloc = f":{parsed.password}@{netloc}"
        parsed = parsed._replace(netloc=netloc)
    return urlunparse(parsed)


CELERY_BROKER_URL = _sanitize_redis_url(REDIS_URL)
CELERY_RESULT_BACKEND = _sanitize_redis_url(REDIS_URL)
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    "global_keyprefix": "celery_result:",
}
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
