# Generated by Django 6.0.3 on 2026-05-20 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customer_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='models3d/files/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='models3d/thumbnails/')),
                ('category', models.CharField(choices=[('gltf_glb', 'glTF / GLB'), ('fbx', 'FBX'), ('obj', 'OBJ'), ('stl', 'STL'), ('other', '其他')], db_index=True, max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to='customers.customer')),
            ],
            options={
                'db_table': 'models3d_items',
                'ordering': ['-updated_at'],
            },
        ),
    ]
