# Generated by Django 6.0.3 on 2026-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_nickname'),
        ('models3d', '0005_alter_modelasset_file_paths'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='modelcategory',
            name='uq_model3d_cat_cust_name',
        ),
        migrations.AddConstraint(
            model_name='modelcategory',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='uq_model3d_category_customer_name'),
        ),
    ]
