# Generated by Django 6.0.3 on 2026-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0006_remove_modelcategory_uq_model3d_cat_cust_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelasset',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='compressed_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='models3d/compressed/'),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='compressed_file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='compression_status',
            field=models.CharField(choices=[('pending', '待压缩'), ('processing', '压缩中'), ('completed', '已完成'), ('failed', '压缩失败'), ('skipped', '跳过')], db_index=True, default='pending', max_length=20),
        ),
    ]
