# Generated by Django 6.0.3 on 2026-05-19 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_alter_customer_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Texture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("file", models.FileField(upload_to="textures/files/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="textures/thumbnails/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("color_map", "颜色贴图"),
                            ("environment_map", "环境贴图"),
                            ("opacity_map", "透明度贴图"),
                            ("lighting_map", "光照贴图"),
                            ("normal_map", "法线贴图"),
                            ("pbr_map", "PBR 贴图"),
                            ("physical_map", "物理贴图"),
                            ("scene_environment", "场景环境贴图"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "texture_slot",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textures",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "texture_items",
                "ordering": ["-updated_at"],
            },
        ),
    ]
