# Generated by GPT on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):
    """
    把 customers app 的表名从 Django 默认的 `customers_customer`
    重命名为业务更清晰的 `customer_accounts`。

    说明：
    - 这是“重命名表”，不会丢数据
    - 同时更新 Django 的 state，让 ORM 知道新的 db_table
    """

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE customers_customer RENAME TO customer_accounts;",
                    reverse_sql="ALTER TABLE customer_accounts RENAME TO customers_customer;",
                )
            ],
            # 更新 migration state，让 Django 知道模型对应的新表名，
            # 避免每次 migrate 都提示“models 有改动但未生成迁移”。
            state_operations=[
                migrations.AlterModelTable(name="customer", table="customer_accounts"),
            ],
        )
    ]

