# Generated by Django 6.0.3 on 2026-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerpublicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
